#!/usr/bin/env python3
"""contributors — a collaboration map over the memory docs.

Scans `memory/ideas.md` and `memory/hypothesis-graveyard.md`, splits them into entries
(one per `###` heading), and classifies each by who contributed — Fable, Codex, or both —
from signatures and credit phrases. Renders `COLLABORATION.md` so joint ideas are legible.

Heuristic: an entry is *collaborative* when it references both agents (a Fable/Claude
signature AND Codex, or an explicit credit like "design credit: Codex" / "reconstructed by
Fable"). It gets sharper as both agents sign their work (see AGENTS.md / CLAUDE.md).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS = [
    _REPO_ROOT / "memory" / "hypothesis-graveyard.md",
    _REPO_ROOT / "memory" / "ideas.md",
]

FABLE = re.compile(r"\bfable\b|\bclaude\b|\bopus\b", re.I)
CODEX = re.compile(r"\bcodex\b|\bgpt\b", re.I)
COLLAB_MARKERS = re.compile(r"design credit|reconstructed by|resolves? (?:the )?codex|codex/fable|cross-agent|discrepancy", re.I)


def split_entries(text: str) -> list[tuple[str, str]]:
    """Return (title, body) for each '### ' heading section."""
    entries: list[tuple[str, str]] = []
    current_title: str | None = None
    buf: list[str] = []
    for line in text.splitlines():
        if line.startswith("### "):
            if current_title is not None:
                entries.append((current_title, "\n".join(buf)))
            current_title = line[4:].strip()
            buf = []
        elif current_title is not None:
            buf.append(line)
    if current_title is not None:
        entries.append((current_title, "\n".join(buf)))
    return entries


def classify(title: str, body: str) -> str:
    text = f"{title}\n{body}"
    has_fable = bool(FABLE.search(text))
    has_codex = bool(CODEX.search(text))
    if (has_fable and has_codex) or COLLAB_MARKERS.search(text):
        return "collaborative"
    if has_codex:
        return "codex"
    if has_fable:
        return "fable"
    return "unattributed"


def short(title: str) -> str:
    return title.split(":")[0].strip() if ":" in title else title[:60]


def build_map() -> dict[str, list[str]]:
    buckets: dict[str, list[str]] = {"collaborative": [], "fable": [], "codex": [], "unattributed": []}
    for doc in DOCS:
        if not doc.exists():
            continue
        for title, body in split_entries(doc.read_text(encoding="utf-8")):
            buckets[classify(title, body)].append(title.strip())
    return buckets


def render(buckets: dict[str, list[str]]) -> str:
    total = sum(len(v) for v in buckets.values())
    lines = [
        "# Collaboration Map — Fable ⇄ Codex",
        "",
        f"_Auto-generated by `agent_bus/contributors.py` from the memory docs. {total} entries._",
        "Heuristic from signatures + credit phrases; sharpens as both agents sign their work.",
        "",
        f"**Collaborative: {len(buckets['collaborative'])} · Fable-led: {len(buckets['fable'])} · "
        f"Codex-led: {len(buckets['codex'])} · Unattributed: {len(buckets['unattributed'])}**",
        "",
    ]
    labels = {
        "collaborative": "🤝 Collaborative (both Fable and Codex)",
        "fable": "🔵 Fable-led",
        "codex": "🟠 Codex-led",
        "unattributed": "⚪ Unattributed (predates signing)",
    }
    for key in ("collaborative", "fable", "codex", "unattributed"):
        lines.append(f"## {labels[key]}")
        if not buckets[key]:
            lines.append("_(none)_")
        for title in buckets[key]:
            lines.append(f"- {title}")
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    buckets = build_map()
    out = _REPO_ROOT / "COLLABORATION.md"
    out.write_text(render(buckets), encoding="utf-8")
    counts = {k: len(v) for k, v in buckets.items()}
    print(f"wrote {out.name}: {counts}")
    if "--show" in sys.argv:
        print("\ncollaborative:")
        for t in buckets["collaborative"]:
            print(f"  - {t}")


if __name__ == "__main__":
    main()
